{
 "title": "Image Librarian Events",
 "description": "Events of Image Librarian",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Object Count",
   "type": "timeseries",
   "description": "Number of object by date",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  object_id,\n  UNIX_TIMESTAMP(datetime) AS \"time\",\n  count(object_id) AS \"count\"\nFROM image_objects\nWHERE\n  $__timeFilter(datetime) and object_id = 'car'\nGROUP BY datetime\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  object_id,\n  UNIX_TIMESTAMP(datetime) AS \"time\",\n  count(object_id) AS \"count\"\nFROM image_objects\nWHERE\n  $__timeFilter(datetime) and object_id = 'person'\nGROUP BY datetime\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  object_id,\n  UNIX_TIMESTAMP(datetime) AS \"time\",\n  count(object_id) AS \"count\"\nFROM image_objects\nWHERE\n  $__timeFilter(datetime) and object_id = 'dog'\nGROUP BY datetime\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  object_id,\n  UNIX_TIMESTAMP(datetime) AS \"time\",\n  count(object_id) AS \"count\"\nFROM image_objects\nWHERE\n  $__timeFilter(datetime) and object_id = 'cat'\nGROUP BY datetime\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  object_id,\n  UNIX_TIMESTAMP(datetime) AS \"time\",\n  count(object_id) AS \"count\"\nFROM image_objects\nWHERE\n  $__timeFilter(datetime) and object_id = 'truck'\nGROUP BY datetime\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Temperature/Humidity Sensors",
   "type": "timeseries",
   "description": "Temp and Humidity by datetime",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(Value as DECIMAL) AS \"Temp\",\r\n  UNIX_TIMESTAMP(datetime) AS \"time\"\r\nFROM events\r\nWHERE\r\n  $__timeFilter(datetime) and Event = 'Temp'\r\nGROUP BY datetime, camera_id\r\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\r\n  CAST(Value as DECIMAL) AS \"Humidity\",\r\n  UNIX_TIMESTAMP(datetime) AS \"time\"\r\nFROM events\r\nWHERE\r\n  $__timeFilter(datetime) and Event = 'humidity'\r\nGROUP BY datetime, camera_id\r\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "License Frequency",
   "type": "table",
   "description": "How often a license plate appeared on our street",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  license_plates.license as \"License#\",\n  license_plates.color,\n  license_plates.type,\n  license_plates.identified,\n  count(alpr_events.license_id) as \"count\"\nFROM alpr_events\ninner join license_plates on alpr_events.license_id = license_plates.ID\nWHERE $__timeFilter(alpr_events.datetime)\ngroup by alpr_events.license_id\nORDER BY count desc"
    },
    {
     "rawSql": "SELECT\n  license_plates.license as \"License#\",\n  license_plates.color,\n  license_plates.type,\n  license_plates.identified,\n  count(alpr_events.license_id) as \"count\"\nFROM alpr_events\ninner join license_plates on alpr_events.license_id = license_plates.ID\nWHERE $__timeFilter(alpr_events.datetime) AND license_plates.identified = 'unknown'\ngroup by alpr_events.license_id\nORDER BY count desc"
    }
   ]
  },
  {
   "title": "Current Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Value AS \"Value\"\nFROM events\nWHERE\n  $__timeFilter(datetime) AND\n  Event = \"Temp\" AND camera_id = 11\nORDER BY datetime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nValue\r\nFROM events\r\nWHERE\r\n  $__timeFilter(datetime) AND\r\n  Event = \"humidity\" AND camera_id = 11\r\nORDER BY datetime DESC LIMIT 1"
    }
   ]
  }
 ]
}